// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ZlQBAJdnQcD1u85ES86_oPK_J03jUnc',
    appId: '1:537588246826:web:b617633b3baac140029653',
    messagingSenderId: '537588246826',
    projectId: 'todo-a800f',
    authDomain: 'todo-a800f.firebaseapp.com',
    storageBucket: 'todo-a800f.firebasestorage.app',
    measurementId: 'G-88SMRFBYM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMPUeOzwzK_ymxJTfCYMPmp9-fT0qvq0',
    appId: '1:537588246826:android:76fa9a247e3d9acc029653',
    messagingSenderId: '537588246826',
    projectId: 'todo-a800f',
    storageBucket: 'todo-a800f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9q_SZEsg_Kmib_Nv_9MxuatjxPzz_z1I',
    appId: '1:537588246826:ios:e2cf815ccef89cc8029653',
    messagingSenderId: '537588246826',
    projectId: 'todo-a800f',
    storageBucket: 'todo-a800f.firebasestorage.app',
    iosClientId: '537588246826-c3qu5erl0e274hve2ib7811nt39ifiil.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9q_SZEsg_Kmib_Nv_9MxuatjxPzz_z1I',
    appId: '1:537588246826:ios:e2cf815ccef89cc8029653',
    messagingSenderId: '537588246826',
    projectId: 'todo-a800f',
    storageBucket: 'todo-a800f.firebasestorage.app',
    iosClientId: '537588246826-c3qu5erl0e274hve2ib7811nt39ifiil.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ZlQBAJdnQcD1u85ES86_oPK_J03jUnc',
    appId: '1:537588246826:web:c4a89ab8a1a40e6b029653',
    messagingSenderId: '537588246826',
    projectId: 'todo-a800f',
    authDomain: 'todo-a800f.firebaseapp.com',
    storageBucket: 'todo-a800f.firebasestorage.app',
    measurementId: 'G-C2EJGE04ZY',
  );
}
